server:
    port: 8080
    compression:
        min-response-size: 512
        enabled: true
        mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
    #undertow服务器的配置
    undertow:
        io-threads: 4
        worker-threads: 10
        buffer-size: 16384
        accesslog:
            enabled: true
            dir: arget/logs
            pattern: combined
#打印日志配置
logging:
    config: classpath:logback-spring.xml
    path: /Users/jcala/logs
#velocity模板引擎的配置
spring:
    velocity:
        cache: false
        view-names: error,index,projects,tags,tagView,archives,post,about,login,admin/blog_add,admin/project,
                    admin/moniter,admin/blog_modify,admin/blog_list,admin/info,admin/result,admin/resume
        properties:
          velocimacro.library: VM_global_library.vm
          directive.parse.max.depth: 2
    http:
        encoding.charset: UTF-8
        encoding.force: false
        multipart:
          max-file-size: 3MB
          max-request-size: 10MB
    cache:
      cache-names: ehcache
      ehcache:
        config: ehcache.xml
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/jcala_blog?useUnicode:true&amp;characterEncoding:UTF-8
      driverClassName: com.mysql.jdbc.Driver
      hikari:
        connection-timeout: 30000
        maximum-pool-size: 50
        minimum-idle: 5
mybatis:
    type-aliases-package: me.jcala.blog.domain,me.jcala.blog.mapping
    type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler
    config-location: classpath:mybatis-config.xml
reverse:
    domain: http://127.0.0.1
    port: 8090
    prefix: jcala_blog
    path: /home/jcala/blog
